attempt 11 to isolate slow pipeline

diff --git a/scripts/run-e2e-tests b/scripts/run-e2e-tests
--- a/scripts/run-e2e-tests
+++ b/scripts/run-e2e-tests
@@ -27,20 +27,21 @@ fi
 failedTests=()
 for file in $allTestFiles
 do
-  if ! maestro test "$file" -e APP_ID="$APPID";
-  then
-    echo "Test ${file} failed. Retrying in 30 seconds..."
-    sleep 30
-    if ! maestro test "$file" -e APP_ID="$APPID";
-    then
-      echo "Test ${file} failed again. Retrying for the last time in 120 seconds..."
-      sleep 120
-      if ! maestro test "$file" -e APP_ID="$APPID";
-      then
-        failedTests+=("$file")
-      fi
-    fi
-  fi
+  maestro test "$file" -e APP_ID="$APPID";
+  # if ! maestro test "$file" -e APP_ID="$APPID";
+  # then
+  #   echo "Test ${file} failed. Retrying in 30 seconds..."
+  #   sleep 30
+  #   if ! maestro test "$file" -e APP_ID="$APPID";
+  #   then
+  #     echo "Test ${file} failed again. Retrying for the last time in 120 seconds..."
+  #     sleep 120
+  #     if ! maestro test "$file" -e APP_ID="$APPID";
+  #     then
+  #       failedTests+=("$file")
+  #     fi
+  #   fi
+  # fi
 done
 
 if [ ${#failedTests[@]} -eq 0 ]; then
